# Generated by Django 5.1 on 2024-08-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='initial_code',
            field=models.TextField(blank=True),
        ),
    ]
